### ISSUE TITLE
Callbacks / Deferred callbacks? 

### ISSUE THREAD

**Issue by KingScooty** [beezee/djax#20]
It'd be really nice if this plugin had callbacks.

I know we can bind to the `$(window)` for `djaxLoad` events and `djaxClick` events, but i don't necessarily want the new content injected into the `DOM` before i've decided what i want to do with it.

How would i go about exposing the callbacks?

**Comment by KingScooty** [comment]
For instance, say if i wanted transitions/animations between pages - whether that be a fade or slide similar to GitHubs tree navigation.

**Comment by beezee** [comment]
The short answer to this
-    accept callbacks as args (probably justifies a refactor to an options object instead of growing the parameter list)
-    check if they are set and callable in the appropriate spots (I'd put one in attachClick, one before ajax in navigate and one after ajax in navigate off the top of my head, onClick, onBeforeNavigate, onAfterNavigate) and call them if yes.
-    allow ability to halt process from callback by explicitly returning false so call them something like this
  
  ```
  if (typeof onClick === 'function' && onClick() === false) return;
  ```

This one has some design choices involved so it may be some time before I get to look into it, but I would be more than happy to merge a pull request for it.

**Comment by g5604** [comment]
Any progress on this? dJax is working great for me, but I need to delay the incoming content until after the existing content has faded out.

**Comment by o-l-e** [comment]
+1

**Comment by beezee** [comment]
This was introduced here - https://github.com/beezee/djax/pull/23

Closing as resolved, much thanks to @tony2nite
