### ISSUE TITLE
Make loaded page result available

### ISSUE THREAD

**Issue by GaryJones** [beezee/djax#5]
As well as the URL and title from the loaded page, is it possible to make the whole result available to djaxLoad too?

For the WordPress theme I'm using (Genesis child theme), the layout between, say, content-sidebar and sidebar-content is done purely via the body class, so while djax is correctly loading the contents of #content and #sidebar, it's not displaying the sidebar in the right place, as the body class is for the original page.

I imagine other themes or pages might want the body ID, the html class / ID, or some other part too, so making the whole new page markup available within the data for djaxLoad means they can pick out which parts they need and update the new page accordingly.

**Comment by beezee** [comment]
The issue with the body class affecting sub containers is exactly why I went with the bones theme for my demo (that theme thankfully avoids those practices.)

Either way this is a great suggestion and an easy tweak, it's been implemented and the readme updated accordingly

**Comment by DavidOliver** [comment]
I'm a JavaScript novice and new to the pjax/djax approach (but think I really like it - thanks!), and have a couple of questions on this issue.

> I imagine other themes or pages might want the body ID, the html class / ID, or some other part too, so making the whole new page markup available within the data for djaxLoad means they can pick out which parts they need and update the new page accordingly.

Firstly, if I understand correctly, this means that to update the body classes I'd need to write a little custom JavaScript/jQuery that picks out the body classes from the complete returned result and apply it to the existing body tag. Is that correct?

Secondly, isn't returning the whole response like this partially negating the data size benefit of djax, in that the whole of the page's HTML data is returned rather than only the updated portions? I appreciate it's necessary to handle body classes, but when djax is only being used to update a relatively small part of a page and body classes are not required, would it be an idea to be able to turn the loaded page result off?

**Comment by DavidOliver** [comment]
I've done a bit more reading on pjax, and I'm not sure but it seems that one way djax differs is that no server-side configuration is required, which I think means the whole page response is returned anyway? This would make my second question above irrelevant.

**Comment by beezee** [comment]
Hi David- 

First question - yes that's right, you'd hang that code on the [djaxLoad callback](http://beezee.github.com/djax.html#events/djaxload)

Second question - no such data size benefit actually exists. The full page is requested every time djax grabs a page, at which point djax is doing a comparison to the current DOM and rendering out only what has changed.

You'd have to write your server side code to render partial pages if you were after such a performance benefit- an ajax call is not capable of picking which parts of a server response it wants to retrieve, rather the server has the choice to serve more or less content.

That said, I can't see such an optimization being worth the effort, since you're essentially loading a smaller or larger string of HTML- the browser doesn't process it or download any assets til it's rendered in the current DOM, which basically means you're focusing on the difference of the string length of a js variable. Unlikely to impact load times at all, more likely that it would impact memory consumption of the browser. You'd have to use a profiler to measure but even that I'd assume to be miniscule in most common scenarios.

**Comment by DavidOliver** [comment]
@beezee , many thanks for the response.

I kind of twigged the answer to the second question (see previous message) once I read about setting up server config for pjax and looking for its header and setting no layout for Rails, for example. I use [Symphony CMS](http://getsymphony.com/), and whilst I'm sure it's possible to restrict the content returned in this way I'd rather stick with djax so that I don't have to worry about this and also have the flexibility of defining more than one update area.

Thanks again!

**Comment by beezee** [comment]
My pleasure David - skipping that server side stuff was exactly why I put this together so I totally understand
